:set number
:set mouse=a
:set smarttab
:set smartindent
:set expandtab
:set smartcase
:set tabstop=2
:set shiftwidth=2 
:set encoding=UTF-8
:set clipboard+=unnamedplus
:set signcolumn=yes
:set splitbelow
:set splitright
:set nowrap
:set hidden
:set nobackup
:set nowritebackup
:set cmdheight=2
:set updatetime=300
let mapleader = " "
